"""Upgrade the deployed conv/1 bridge to announce conv/2; never deploys or restarts anything.

Input must be the production bridge generated by the previous prepare_bridge.py
(SHA-256 below). Output is byte-identical to prepare_bridge.py applied to the original
inspected source, so both paths yield the same reviewed candidate.
"""
from pathlib import Path
import hashlib
import sys

from prepare_bridge import CAPABILITY_EXPRESSION, CONVERSATION_IMPORT

DEPLOYED_CONV1 = "2563695d3166ef7206d7553f92c1fe189bcfe0cfd0a76510206faeb9aa91676e"
OLD_IMPORT = "from conversation import ConversationService, create_conversation_agent, valid_ref"
OLD_CAPABILITIES = '(["conv/1"] if self.conversation else [])'


def upgrade(source, target):
    raw = Path(source).read_bytes()
    if hashlib.sha256(raw).hexdigest() != DEPLOYED_CONV1:
        raise ValueError("Deployed bridge differs from the reviewed conv/1 version; review before upgrading")
    text = raw.decode("utf-8")
    for old, new in ((OLD_IMPORT, CONVERSATION_IMPORT), (OLD_CAPABILITIES, CAPABILITY_EXPRESSION)):
        if text.count(old) != 1:
            raise ValueError("Expected unique bridge integration point")
        text = text.replace(old, new)
    compile(text, "candidate_bridge.py", "exec")
    # Do not translate LF to CRLF on Windows; the deployment candidate is hash-pinned.
    Path(target).write_bytes(text.encode("utf-8"))


if __name__ == "__main__":
    upgrade(sys.argv[1], sys.argv[2])
